"""add message_type and file_url to message

Revision ID: b2fb8093154a
Revises: 5970e7412e6d
Create Date: 2026-03-05 19:10:00.321935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b2fb8093154a'
down_revision: Union[str, Sequence[str], None] = '5970e7412e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    messagetype = sa.Enum('text', 'image', 'voice', name='messagetype')
    messagetype.create(op.get_bind(), checkfirst=True)
    op.add_column('message', sa.Column('message_type', messagetype, nullable=False, server_default='text'))
    op.add_column('message', sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'file_url')
    op.drop_column('message', 'message_type')
    # ### end Alembic commands ###
